# -*- coding: utf-8 -*-
"""assignment 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zOwLhI5VAUdp5cGy9QFErGr-sxMRvrwK
"""

# Date 30/09/2023
# CSC461 – Assignment2 – Regular Expressions
#  Full Name =Eisha khawaja
#  Registration Number=fa21-bse-084
# A brief description of the task The code uses Python's regular expressions (re module) to process a given text.
#1 It extracts all words, words starting with capital letters, and words of specific lengths or patterns from the text.
#2 The code also identifies words within double quotes and pulls out individual vowel characters.
#3 Additionally, it cleans the text by removing punctuation, converting contractions, and replacing newlines with spaces.
#4 Each operation results in a list of words or a modified version of the original text.

import re

from google.colab import drive
drive.mount('/content/drive')

file_path = "/content/drive/My Drive/example-text.txt"

with open(file_path, 'r') as file:
    text = file.read()

#1 it will extract list of all words.

words=re.findall(r'\w+',text)
print(words)

#2 It will extract list of all words starting with a capital letter

capital_words=re.findall(r'[A-Z]\w+',text)
print(capital_words)

#3 it will extract list of all words of length 5.

length_five=re.findall(r'\w{5}',text)
print(length_five)

#4  it will extract list of all words inside double quotes.

double_quotes=re.findall(r'\"(\w+)\"',text)
print(double_quotes)

#5 It will extract list of all vowels

vowels=re.findall('[aeiouAEIOU]',text)
print(vowels)

#6 It will extract list of all 3 letter word ending with letter e

words = re.findall(r'\w{2}e', text)
print(words)

#7nit will extract list of all words starting and ending with letter ‘b’.

b_words = re.findall(r'\bb\w*b\b', text)
print(b_words)

#8 It will remove all punctuation marks from the text.

no_punc=re.sub(r'[\W]','',text)
print(no_punc)

#9 it will replace all words ending ‘n't’ to their full form ‘not’.

rep=re.sub('\w+n\'t','not',text)
print(rep)

#!0 replace new line with text

newline=re.sub(r'\n','',text)
print(newline)