# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hEDevlLyUmGGx70AMBG3I0k2C78NLlQB
"""

import requests
from bs4 import BeautifulSoup
import time
import pandas as pd

film_links = [
    "https://www.imdb.com/title/tt1375666/",
    "https://www.imdb.com/title/tt0816692/",
    "https://www.imdb.com/title/tt0109830/",
    "https://www.imdb.com/title/tt0133093/",
    "https://www.imdb.com/title/tt0107290/"
]

request_headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36'
}

def get_film_details(film_url):
    resp = requests.get(film_url, headers=request_headers)
    parsed_content = BeautifulSoup(resp.content, 'html.parser')

    film_name_tag = parsed_content.find("h1").find("span")
    film_name = film_name_tag.text.strip() if film_name_tag else "Name Unavailable"

    rating_tag = parsed_content.find("span", class_="sc-bde20123-1 iZlgcd")
    film_rating = rating_tag.text if rating_tag else "Rating Unavailable"

    return {"Film Name": film_name, "Film Rating": film_rating}

film_data = []

for link in film_links:
    details = get_film_details(link)
    film_data.append(details)
    time.sleep(1)

film_df = pd.DataFrame(film_data)
film_df.to_excel('film_data.xlsx', index=False)