# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n-j2IRBrPwtQt3dqSQUOE7Pfg9n_zv0-
"""

import requests
from bs4 import BeautifulSoup

def fetch_celebrities_sharing_birthday():
    base_url = "https://www.timeanddate.com/on-this-day/august/29"
    response = requests.get(base_url)
    page_content = BeautifulSoup(response.content, "html.parser")

    birthday_celebrities = page_content.find("div", class_="otd-life__block").text.strip()
    print(birthday_celebrities)

    return birthday_celebrities

def fetch_historic_events():
    base_url = "https://www.britannica.com/on-this-day/august-29"
    response = requests.get(base_url)
    page_content = BeautifulSoup(response.content, "html.parser")

    historic_events = []

    event_sections = page_content.findAll("div", class_="card-body")
    event_dates = page_content.findAll("div", class_="date-label")

    for index in range(len(event_sections)):
        event_detail = {
            "event_date": event_dates[index].text.strip(),
            "description": event_sections[index].text.strip()
        }
        historic_events.append(event_detail)

    print("\nHistoric Events that happened on this day: ")
    for event in historic_events:
        print(f"{event['event_date']}: {event['description']}")

    return historic_events

celebrities_with_same_birthday = fetch_celebrities_sharing_birthday()

with open("birthday_results.txt", "w") as results_file:
    results_file.write("Famous Personalities Sharing Your Birthday:\n")
    results_file.write(celebrities_with_same_birthday)
    results_file.write("\n\nHistoric Events on Your Birthday:\n")

    for event in fetch_historic_events():
        results_file.write(f"{event['event_date']}: {event['description']}\n\n")